# Copyright (c) 2018 SPARKL Limited. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Author <ahfarrell@sparkl.com> Andrew Farrell
# Installs svc_blockchain dependencies on Ubuntu14
#
  - set_fact: regular_user_id={{ ansible_user_id }}
    when: regular_user_id is undefined

  - set_fact: blockchain_home="/home/{{ regular_user_id }}/.blockchain"
    when: blockchain_home is undefined

  - name: ensure blockchain directory
    file: path={{ blockchain_home }} state=directory owner={{ regular_user_id }} mode=0775
    become: yes

  - name: ensure sample blockchain directories - local
    file: path={{ blockchain_home }}/local state=directory owner={{ regular_user_id }} mode=0775
    become: yes

  - apt: name={{ item }} state=present update_cache=yes
    with_items:
    - python3-dev
    become: yes

  - name: python dependencies
    pip: name={{ item }} executable=pip3 state=present
    with_items:
    - ed25519
    - twython
    become: yes
